import { Injectable } from '@angular/core';
import { GodDetails } from '../models/god-details';

@Injectable({
  providedIn: 'root'
})
export class GodDetailsService {

  private AllGods: GodDetails[] = [];

  constructor(){
    this.AllGods = [
      {
        Key: "Ganapathi",
        Name: 'Sri Ganapathi',
        Content: [
          "One day Goddess Parvati was at home on Mt.Kailash preparing for a bath. As she didn’t want to be disturbed, she told Nandi, her husband Shiva’s Bull, to guard the door and let no one pass. Nandi faithfully took his post, intending to carry out Parvati’s wishes. But, when Shiva came home and naturally wanted to come inside, Nandi had to let him pass, being loyal first to Shiva. Parvati was angry at this slight, but even more than this, at the fact that she had no one as loyal to Herself as Nandi was to Shiva. So, taking the turmeric paste (for bathing) from her body and breathing life into it, she created Ganesha, declaring him to be her own loyal son.",
          "The next time Parvati wished to bathe, she posted Ganesha on guard duty at the door. In due course, Shiva came home, only to find this strange boy telling him he couldn’t enter his own house! Furious, Shiva ordered his army to destroy the boy, but they all failed! Such power did Ganesha possess, being the son of Devi Herself!",
          "This surprised Shiva. Seeing that this was no ordinary boy, the usually peaceful Shiva decided he would have to fight him, and in his divine fury severed Ganesha’s head, killing him instantly. When Parvati learned of this, she was so enraged and insulted that she decided to destroy the entire Creation! Lord Brahma, being the Creator, naturally had his issues with this, and pleaded that she reconsider her drastic plan. She said she would, but only if two conditions were met: one, that Ganesha be brought back to life, and two, that he be forever worshipped before all the other gods.",
          "Shiva, having cooled down by this time, and realizing his mistake, agreed to Parvati’s conditions. He sent Brahma out with orders to bring back the head of the first creature he crosses that is laying with its head facing North. Brahma soon returned with the head of a strong and powerful elephant, which Shiva placed onto Ganesha’s body. Breathing new life into him, he declared Ganesha to be his own son as well and gave him the status of being foremost among the gods, and leader of all the ganas (classes of beings), Ganapati.",
          "At first glance, this story just seems like a nice tale that we might tell our children or a myth without any real substance. But, it’s true mystical meaning is veiled. It is explained thus:",
          "Parvati is a form of Devi, the Parashakti (Supreme Energy). In the human body, She resides in the Muladhara chakra as the Kundalini shakti. It is said that when we purify ourselves, ridding ourselves of the impurities that bind us, then the Lord automatically comes. This is why Shiva, the Supreme Lord, came unannounced as Parvati was bathing.",
          "Nandi, Shiva’s bull, who Parvati first sent to guard the door represents the divine temperament. Nandi is so devoted to Shiva that his every thought is directed to Him, and he is able to easily recognize the Lord when He arrives. This shows that the attitude of the spiritual aspirant is what gains access to Devi’s (the kundalini shakti’s) abode. One must first develop this attitude of the devotee before hoping to become qualified for the highest treasure of spiritual attainment, which Devi alone grants.",
          "After Nandi permitted Shiva to enter, Parvati took the turmeric paste from Her own body, and with it created Ganesha. Yellow is the colour associated with the Muladhara chakra, where the kundalini resides, and Ganesha is the deity who guards this chakra. Devi needed to create Ganesha, who represents the earthbound awareness, as a shield to protect the divine secret from unripe minds. It is when this awareness begins to turn away from things of the world, and toward the Divine, as Nandi had, that the great secret is revealed.",
          "Shiva is the Lord and Supreme Teacher. Ganesha here represents the ego-bound Jiva. When the Lord comes, the Jiva, surrounded as it is with the murky cloud of ego, usually doesn’t recognize Him, and maybe even ends up arguing or fighting with Him! Therefore, it is the duty of the Lord, in the form of the Guru, to cut off the head of our ego! So powerful is this ego, however, that at first, the Guru’s instructions may not work, as Shiva’s armies failed to subdue Ganesha. It often requires a tougher approach, but, eventually the compassionate Guru, in His wisdom finds a way.",
        ]
      },
      {
        Key: 'VenkateshwaraSwamy',
        Name: 'Sri Lakshmi Padmavathi sametha Venkateswara Swamy',
        Content: [
          "Lakshmi or Sri Devi is the consort of Vishnu. She is the Goddess of wealth and prosperity. Wealth includes nobler values of life, power of mind and intellect, moral, and ethical qualities which constitutes the spiritual wealth. The eight forms of Lakshmi, called Ashta-Lakshmi are: Santhanalakshmi (wealth of progeny), Gajalakshmi (wealth of animals), Dhanalakshmi (wealth of gold and other material wealth), Dhaanyalakshmi (wealth of food grains), Veeralakshmi (wealth of valor), Vijayalaksmi (wealth of victories and success), Mahalakshmi (wealth of greatness) and Aadhilakshmi.",
          "Goddess Padmavati is regarded as the consort of Lord Shrinivasa, who is also worshipped by other names like Venkateswara, Venkatachalapathy and Balaji. Since Padmavati Devi is considered to be an incarnation of Goddess Lakshmi, her consort is Shrinivasa, an avatar of Lord Vishnu. Padmavati or Padmavati Thayar is also referred to by other names such as Alamelu Mangai or Alamelu Mangai Thayar.",
          "While Lord Shrinivasa is revered in a big temple at the summit of the Tirumala hills, in Tirupati, the Padmavathi Ammavari Temple, devoted exclusively to Goddess Padmavati is located in Tiruchanur, close to Tirupahi. It is a tradition that every devotee heading to Tirupati needs to pay homage at this holy shrine prior to visiting the Tirumala Venkateswara Temple, the main temple of his consort. Her temple is deemed to be held in high regard and is an extremely respected and venerated sacred site in South India. It draws thousands of devout worshippers every day.",
          "The temple town of Tirupati is situated at the foot of Tirumala hills in the Chandragiri Taluka of the Chittor district in Andhra Pradesh. The sacred spot on the hill about 2,800 feet above sea level is known as Tirumala, the abode of Lord Venkateswara. The hill forms part of the Eastern Ghats and is also known as Venkatachala and Seshachala. It is said that the Eastern Ghats on this side along with their curves, heights and falls resemble the serpent Adisesha and that the seven hills of Tirupati are its seven heads and Ahobalam where Lord Narasimha murthy is worshipped, representing the centre of Adisesha, and Srisailam representing the tail end of Adisesha. That is why Tirumala is called Seshachala. According to the legends, this has been a sacred place in all the four yugas, and was known as Vrishabhachala in the Krithayuga, Anjanachala in the Tretayuga, Seshachala in the Dwaparayuga and Venkatachala in the present Kaliyuga.",
          "In this temple, unlike other Vishnu temples, we find no minor shrines or idols of Vaishnava saints. Apart from the Lord Venkateswara temple, the other important places at Tirumala and Swami pushkarini, Papavinasam and Akasaganga waterfalls, Varahaswamy temple, and Shila Toranam a very ancient rock formation supposed to be over 10,000 years old.",
          "Once some rishis headed by Kasyapa began to perform a sacrifice on the banks of the Ganges. Sage Narada visited them and asked them why they were performing the sacrifice and who would be pleased by it. Not being able to answer the question, the rishis approached Sage Bhrigu. To reach a solution after a direct ascertainment of reality, Sage Bhrigu first went to Satyaloka, the abode of Lord Brahma. At Satyaloka, he found Lord Brahma, reciting the four Vedas in praise of Lord Narayana, with each of his four heads, and attended upon by Saraswati. Lord Brahma did not take notice of Bhrigu offering obeisance. Concluding that Lord Brahma was unfit for worship, Bhrigu left Satyaloka for Kailasa, the abode of Lord Shiva. At Kailasa, Bhrigu found Lord Siva spending his time pleasantly with Parvati and not noticing his presence. Parvati drew the attention of Siva to the presence of the sage. Lord Siva was furious at Bhrigu's intrusion and tried to destroy him. The sage cursed Lord Siva and left for Vaikuntam. At Vaikuntam, Lord Vishnu was reposing on Adisesha with Sri Mahalakshmi in service at His feet. Finding that Lord Vishnu also did not notice him, the sage was infuriated and kicked the Lord on His chest, the place where Mahalakshmi resides. At once, Lord Vishnu hastened to apologise to the angry sage and pressed his feet to allay the pain caused to Bhrigu's leg. In doing so the Lord removed the eye in the foot of the sage, stripping of his special powers. Thereupon, the sage concluded that Lord Vishnu was the most supreme of the trimurthis and told the rishis the same.",
          "Sri Mahalakshmi was angered by the action of her Lord in apologising to Bhrigu who committed an offence. Out of anger and anguish she left Vaikuntha and resided in Karavirapur now known as Kolhapur. After the departure of Mahalakshmi, a forlorn Lord Vishnu left Vaikuntam and took abode in an ant-hill under a tamarind tree, beside a pushkarini on the Venkata Hill, meditating for the return of Lakshmi, without food or sleep. This was the place where Lord took the form of Varaha to rescue Mother Earth form the deep ocean. Taking pity on Lord Vishnu, Brahma and Maheshwara decided to assume the forms of a cow and its calf to serve Him. Surya, the Sun God informed Mahalakshmi of this and requested her to assume the form of a cowherdess and sell the cow and calf to the king of the Chola country. The king of the Chola country bought the cow and its calf and sent them to graze on the Venkata Hill along with his herd of cattle. Discovering Lord Vishnu on the ant-hill, the cow provided its milk, and thus fed the Lord. Meanwhile, at the palace, the cow was not yielding any milk, for which the Chola Queen chastised the cowherd severely. To find out the cause of lack of milk, the cowherd followed the cow, hid himself behind a bush and discovered the cow emptying her udder over the ant-hill. Incensed over the conduct of the cow, the cowherd aimed a blow with his axe on the head of the cow. However, Lord Vishnu rose from the ant-hill to receive the blow and save the cow. When the cowherd saw the Lord bleed at the blow of his axe, he fell down and died of shock.",
          "Yesoda brought up Sri Krishna, the son of Devaki, in his early years. However, Yasoda was not blessed to witness the marriage of Sri Krishna with Rukmini and she felt very sad. Sri Krishna promised to fulfil her desire in her next birth as Vakuladevi in his next incarnation as Srinivasa. In Rukmini's next birth as Vakuladevi, she was serving Lord Varahaswami when He sent her to serve Srinivasa. Sometime later, a King named Akasa Raja who belonged to the Lunar race was ruling over Thondamandalam. Akasa Raja had no heirs, and therefore, he wanted to perform a sacrifice. As part of the sacrifice, he was ploughing the fields when his plough turned up a lotus in the ground. On examining the lotus, the King found a female child in it. The king was happy to find a child even before he performed a sacrifice and carried it to his place and gave it to his Queen to tend it. At that time he heard an aerial voice which said 'O King, tend it as your child and fortune will befall you'. As she was found in a lotus, the king named her Padmavati. Princess Padmavati grew up into a beautiful maiden and was attended by a host of maids",
          "One day, Lord Srinivasa, who was hunting, chased a wild elephant in the forests surrounding the hills. In the elephant's pursuit, the Lord was led into a garden, where Princess Padmavati and her maids were picking flowers. The sight of the elephant frightened the Princess and her maids. But the elephant immediately turned around, saluted the Lord and disappeared into the forest. Lord Srinivasa, who was following on horse back, and saw the frightened maidens. However, He was repulsed with stones thrown at Him by the maids. He returned to the hills in haste, leaving His horse behind. Vakuladevi found him lying on his bed, not interested in anything. The Lord informed her that unless he married Princess Padmavati. The Lord then narrated the story of her (Padmavati’s) previous birth and his promise to wed her. After listening to Srinivasa's story of how he had promised to marry Vedavati in her next birth as Padmavati, Vakuladevi realised that Srinivasa would not be happy unless he married Padmavati. She offered to go to Akasa Raja and his Queen and arrange for the marriage. On the way she met the maid-servants of Padmavati returning from a Siva Temple. She learnt from them that Padmavati was also pining for Srinivasa. Vakuladevi went along with the maid servants to the Queen",
          "Meanwhile, Akasa Raja and his queen Dharanidevi were anxious about the health of their daughter, Padmavathi. They learnt about Padmavathi's love for Srinivasa of Venkata Hill. Akasa Raja consulted Brihaspati about the marriage and was informed that the marriage was in the best interest of both the parties. Kubera lent money to Lord Srinivasa to meet the expenses of the marriage. Lord Srinivasa, along with his consorts and Lord Brahma and Lord Siva started the journey to the residence of Akasa Raja with his vehicle Garuda. At the palace entrance, Lord Srinivasa was received by Akasa Raja with full honours and taken in procession on a mounted elephant to the palace for the marriage. In the presence of all the Devas, Lord Srinivasa wed Princess Padmavati, thus blessing Akasa Raja.",
        ]
      },
      {
        Key: 'KashiVishwanathaSwamy',
        Name: 'Sri Kashi Vishwanatha Swamy',
        Content: [
          "Shiva is represented in a variety of forms: in a pacific mood with his consort Parvati and son Skanda, as the cosmic dancer (Nataraja), as a naked ascetic, as a mendicant beggar, as a yogi, as a Dalit (formerly called untouchable) accompanied by a dog (Bhairava), and as the androgynous union of Shiva and his consort in one body, half-male and half-female (Ardhanarishvara). He is both the great ascetic and the master of fertility, and he is the master of both poison and medicine, through his ambivalent power over snakes. As Lord of Cattle (Pashupata), he is the benevolent herdsman—or, at times, the merciless slaughterer of the “beasts” that are the human souls in his care. Although some of the combinations of roles may be explained by Shiva’s identification with earlier mythological figures, they arise primarily from a tendency in Hinduism to see complementary qualities in a single ambiguous figure.",
          "Shiva’s female consort is known under various manifestations as Uma, Sati, Parvati, Durga, and Kali; Shiva is also sometimes paired with Shakti, the embodiment of power. The divine couple, together with their sons—Skanda and the elephant-headed Ganesha—are said to dwell on Mount Kailasa in the Himalayas. The six-headed Skanda is said to have been born of Shiva’s seed, which was shed in the mouth of the god of fire, Agni, and transferred first to the river Ganges and then to six of the stars in the constellation of the Pleiades. According to another well-known myth, Ganesha was born when Parvati created him out of the dirt she rubbed off during a bath, and he received his elephant head from Shiva, who was responsible for beheading him. Shiva’s vehicle in the world, his vahana, is the bull Nandi; a sculpture of Nandi sits opposite the main sanctuary of many Shiva temples. In temples and in private shrines, Shiva is also worshipped in the form of the lingam, a cylindrical votary object that is often embedded in a yoni, or spouted dish.",
          "Shiva is usually depicted in painting and sculpture as white (from the ashes of corpses that are smeared on his body) with a blue neck (from holding in his throat the poison that emerged at the churning of the cosmic ocean, which threatened to destroy the world), his hair arranged in a coil of matted locks (jatamakuta) and adorned with the crescent moon and the Ganges (according to legend, he brought the Ganges River to earth from the sky, where she is the Milky Way, by allowing the river to trickle through his hair, thus breaking her fall). Shiva has three eyes, the third eye bestowing inward vision but capable of burning destruction when focused outward. He wears a garland of skulls and a serpent around his neck and carries in his two (sometimes four) hands a deerskin, a trident, a small hand drum, or a club with a skull at the end. That skull identifies Shiva as a Kapalika (“Skull-Bearer”) and refers to a time when he cut off the fifth head of Brahma. The head stuck to his hand until he reached Varanasi (now in Uttar Pradesh, India), a city sacred to Shiva. It then fell away, and a shrine for the cleansing of all sins, known as Kapala-mochana (“The Releasing of the Skull”), was later established in the place where it landed.",
        ]
      },
      {
        Key: 'Poojambike',
        Name: 'Sri Poojambike',
        Content: []
      }
    ]
  }

  public GetDetailsOf(name: string): GodDetails | undefined {
    return this.AllGods.find(g => g.Key == name);
  }


}
